### ISSUE TITLE
Use of outline: none [accessibility]

### ISSUE THREAD

**Issue by ConnectExtend** [the-road-to-learn-react/hackernews-client#10]
Regarding the Basics in React chapter, Styling Components section:
There are two occurrences of `outline: none` in `index.css`.  This style choice is problematic for people who navigate with the keyboard. Would you please remove? Thank you.

reference: WCAG Guideline 2.4

**Comment by rwieruch** [comment]
Yes. Perfect suggestion! Thank you 👍

**Comment by rwieruch** [comment]
Solved in https://github.com/the-road-to-learn-react/hackernews-client/pull/12
