### ISSUE TITLE
Wrong Links at the end of Error Handling section in Chapter 3 

### ISSUE THREAD

**Issue by mkishine** [the-road-to-learn-react/hackernews-client#13]
Links at the end of Error Handling section in Chapter 3 point to commit of Client Cache section.
This patch fixes the problem:

```
Index: manuscript/chapter3.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- manuscript/chapter3.md	(date 1553926587000)
+++ manuscript/chapter3.md	(date 1554154244000)
@@ -1218,8 +1218,8 @@
 
 ### Exercises:
 
-* Confirm your [source code for the last section](http://bit.ly/2HoLAGY)
-  * Confirm the [changes from the last section](http://bit.ly/2HquJnd)
+* Confirm your [source code for the last section](http://bit.ly/2Ukfao7)
+  * Confirm the [changes from the last section](http://bit.ly/2HS0gzu)
 * Read about [React's Error Handling for Components](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html)
 
 ## Axios instead of Fetch
```

**Comment by rwieruch** [comment]
Oops. Can you open a PR for it @mkishine ? Thanks for noticing it!

**Comment by mkishine** [comment]
Hello Robin.
I do not know how to prepare PR in github. I have tried pushing changes into new branch, but github refused to take my credentials. This is why I have sent you patch dump.

Thanks,
Michael.

**Comment by rwieruch** [comment]
Hey @mkishine Check out this manual to create a Pull Request: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork You can fork this repository, add your changes, and open a Pull Request.

**Comment by rwieruch** [comment]
Thank you! Fixed over here https://github.com/the-road-to-learn-react/the-road-to-learn-react/commit/035f4fdd82f439b3ebb934c3e7e49f000d449774

**Comment by mkishine** [comment]
Thanks, Robin!
