### ISSUE TITLE
FAIL Test "has a valid snapshot"

### ISSUE THREAD

**Issue by huesoamz** [the-road-to-learn-react/hackernews-client#17]
`<Button onClick={() => {}} >Give Me More</Button> `

this part
`onClick={() => {}}`

broke the test...i dont know why...

![image](https://user-images.githubusercontent.com/3308717/61411251-53842d00-a8bc-11e9-8ede-7ccd27d0416e.png)

**Comment by rwieruch** [comment]
The test is alright. The snapshot is only saying that you passed an additional onClick function to your button. If that's okay with you, you only need to acknowledge it.

**Comment by huesoamz** [comment]
Maybe that is the confusing part, why the snapshot fail? that will apear when I add on the App.js

`Button.propTypes = {
  onClick: PropTypes.func.isRequired,
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};`

And in the test

`  test('has a valid snapshot', () => {
    const component = renderer.create(
      <Button onClick={() => {}} >Give Me More</Button> //this fail
      //<Button>Give Me More</Button> //old, this works
    );
    const tree = component.toJSON();
    expect(tree).toMatchSnapshot();
  });`

I can't understand why if I passing the "function" the snapshot fail.
Anyway thanks for your support
